# Generated by Django 2.2.28 on 2025-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0002_auto_20210204_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membranetopol',
            name='nb_lipids',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
