# Generated by Django 2.2.28 on 2025-05-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membranes', '0003_auto_20250414_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='membranetopol',
            name='root_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='membranes.MembraneTopol'),
        ),
        migrations.AddField(
            model_name='membranetopol',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
