# Generated by Django 2.2.28 on 2025-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
