# Generated by Django 2.2.28 on 2025-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0002_auto_20250414_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
