# Generated by Django 2.2.28 on 2025-05-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forcefields', '0003_auto_20250414_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcefield',
            name='root_version',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forcefields.Forcefield'),
        ),
        migrations.AddField(
            model_name='forcefield',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
